---
- name: This playbook to install httpd
  hosts: all
  become: true
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: Install_apache

  - name: Start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start_apache
    ignore_errors: yes

  - name: Install apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: Install_apache

  - name: Start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags: start_apache

  - name: Copy index.html file
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

