---
- name: This playbook to install packages via yum
  hosts: all
  become: true
  tasks:
  - name: Install GIT package
    yum:
 #     name: ['tree', 'git', 'gcc', 'wget', 'telnet', 'gzip']
      name: "{{ item }}"
      state: installed
    with_items:
      - make
