---
- name: This playbook to uninstall httpd
  hosts: all
  become: true
  tasks:
  - name: Stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: uninstall httpd package
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

  - name: Stop apache2 service
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstall apache2 package
    yum:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
